Repository SeaweedbrainCY/jellyfin-newsletter, pull requests merged in 2025-08, with the labels that each got.

#50 [Feature] Ignore already sent items in previous newsletter
  .gitignore
  README.md
  config/config-example.yml
  main.py
  source/configuration.py
  source/configuration_checker.py
  source/email_controller.py
  source/utils.py
Labels: enhancement

#53 ci: fix docker images for forked repositories
  .github/workflows/build_and_deploy.yml
  .github/workflows/build_and_deploy_dev.yml
Labels: enhancement

#54 fix: handle tmdb API not found error gracefully
  main.py
Labels: bug

#56 fix: correct escape characters in warning message for last newsletter
  source/utils.py
Labels: Bugfix
